import checkOutRoute from "./checkOutRoute";
import indexRoute from "./indexRoute";
import shopCartRoute from "./shopCartRoute";
import shopCompareRoute from "./shopCompareRoute";
import shopErrorRoute from "./shopErrorRoute";
import loginRouter from "./loginRouter";
import pageAccountRoute from "./pageAcoountRoute";
import blogCategoryBigRoute from "./blogCategoryBigRoute";
import blogCategoryFullwidthRoute from "./blogCategoryFullWidthRoute";
import blogCategoryGridRoute from "./blogCategoryGridRoute";
import blogCategoryListRoute from "./blogCategoryListRoute";
import blogPostFullwidthRoute from "./blogPostFullwidth";
import blogPostLeftRoute from "./blogPostLeftRoute";
import blogPostRightRoute from "./blogPostRightRoute";
import pageAboutRoute from "./pageAboutRoute";
import pageAbout2Route from "./pageAbout2Route";
import pageContactRoute from "./pageContactRoute";
import pageForgotPassword from "./pageForgotPassword";
import pagePrivacyPolicyRoute from "./pagePrivacyPolicyRoute";
import pagePurchaseGuideRoute from "./pagePurchaseGuideRoute";
import registerRoute from "./registerRoute";
import resetPasswordRoute from "./resetPasswordRoute";
import pageTermsRoute from "./pageTermsRoute";
import shopFilterRoute from "./shopFilterRoute";
import shopFullwidthRoute from "./shopFullwidthRoute";
import shopGridLeftRoute from "./shopGridLeftRoute";
import shopGridRightRoute from "./shopGridRightRoute";
import shopInvoiceRoute from "./shopInvoiceRoute";
import shopListLeftRoute from "./shopListLeftRoute";
import shopListRightRoute from "./shopListRightRoute";
import shopProductDetailRoute from "./shopProductDetailRoute";
import shopProductFullRoute from "./shopProductFullRoute";
import shopProductLeftRoute from "./shopProductLeftRoute";
import shopProductRightRoute from "./shopProductRightRoute";
import shopProductVendorRoute from "./shopProductVendorRoute";
import shopWishlistRoute from "./shopWishlistRoute";
import vendorDashboardRoute from "./vendorDashboardRoute";
import vendorDetailsRoute from "./vendorDetailsRoute";
import vendorGuideRoute from "./vendorGuideRoute";
import vendorGridRoute from "./vendorGridRoute";
import vendorListRoute from "./vendorListRoute";

// Init all passport
// initPassportLocal();

const initWebRoutes = (app) => {
  app.use("/", indexRoute);
  app.use("/shop-cart", shopCartRoute);
  app.use("/shop-checkout", checkOutRoute);
  app.use("/shop-compare", shopCompareRoute);
  app.use("/page-404", shopErrorRoute);
  app.use("/blog-category-big", blogCategoryBigRoute);
  app.use("/blog-category-fullwidth", blogCategoryFullwidthRoute);
  app.use("/blog-category-grid", blogCategoryGridRoute);
  app.use("/blog-category-list", blogCategoryListRoute);
  app.use("/blog-post-fullwidth", blogPostFullwidthRoute);
  app.use("/blog-post-left", blogPostLeftRoute);
  app.use("/blog-post-right", blogPostRightRoute);
  app.use("/page-about", pageAboutRoute);
  app.use("/page-about-2", pageAbout2Route);
  app.use("/page-account", pageAccountRoute);
  app.use("/page-contact", pageContactRoute);
  app.use("/page-forgot-password", pageForgotPassword);
  app.use("/page-login", loginRouter);
  app.use("/page-privacy-policy", pagePrivacyPolicyRoute);
  app.use("/page-purchase-guide", pagePurchaseGuideRoute);
  app.use("/page-register", registerRoute);
  app.use("/page-reset-password", resetPasswordRoute);
  app.use("/page-terms", pageTermsRoute);
  app.use("/shop-filter", shopFilterRoute);
  app.use("/shop-fullwidth", shopFullwidthRoute);
  app.use("/shop-grid-left", shopGridLeftRoute);
  app.use("/shop-grid-right", shopGridRightRoute);
  app.use("/shop-invoice-1", shopInvoiceRoute);
  app.use("/shop-invoice-2", shopErrorRoute);
  app.use("/shop-invoice-3", shopErrorRoute);
  app.use("/shop-invoice-4", shopErrorRoute);
  app.use("/shop-invoice-5", shopErrorRoute);
  app.use("/shop-invoice-6", shopErrorRoute);
  app.use("/shop-list-left", shopListLeftRoute);
  app.use("/shop-list-right", shopListRightRoute);
  app.use("/shop-product-detail", shopProductDetailRoute);
  app.use("/shop-product-full", shopProductFullRoute);
  app.use("/shop-product-left", shopProductLeftRoute);
  app.use("/shop-product-right", shopProductRightRoute);
  app.use("/shop-product-vendor", shopProductVendorRoute);
  app.use("/shop-wishlist", shopWishlistRoute);
  app.use("/vendor-dashboard", vendorDashboardRoute);
  app.use("/vendor-details-1", vendorDetailsRoute);
  app.use("/vendor-details-2", shopErrorRoute);
  app.use("/vendor-guide", vendorGuideRoute);
  app.use("/vendors-grid", vendorGridRoute);
  app.use("/vendors-list", vendorListRoute);
};
export default initWebRoutes;
